baseURL = "https://notesgnu.github.io/"
title = "Notes GNU"
theme = "m10c"
paginate = 7
languageCode = "en"
DefaultContentLanguage = "ca"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
enableemoji = true


[params]
    author = "msaliko"
    description = "Sou lliures de copiar"
    google_search = true
    avatar = "avatar.png"
    menu_item_separator = "|"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"

[[menu.main]]
    identifier = "home"
    name = "Inici"
    url = "/"

[[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about/"
    weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  
[[menu.main]]
    identifier = "categories"
    name = "Categs"
    url = "/categories/"


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[params.social]]
    url = "jnorbu8@gmail.com"
    name = "envelope"
    icon = "mail"

[[params.social]]
    url = "https://github.com/notesgnu"
    name = "github"
    icon = "github"

[[params.social]]
    url = "https://twitter.com/manelsales"
    name = "twitter"
    icon = "twitter"

[[params.social]]
    url = "https://mastodon.social/@misaliko"
    name = "mastodon"
    icon = "star"
    
[[params.social]]
    url = "https://croniqueslinux.wordpress.com/"
    name = "wordpress"
    icon = "file-text"
