baseURL = "https://notesgnu.github.io/"
title = "Notes GNU"
theme = "m10c"
paginate = 8
languageCode = "en"
DefaultContentLanguage = "ca"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
enableemoji = true


[params]
    author = "msaliko"
    description = "2024 (CC) Sou lliures de copiar"
    google_search = true
    avatar = "avatar.png" #l'avatar va a la carpeta "static"
    menu_item_separator = " | "

[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  lightColor = "#afbac4"
  lightestColor = "#ffffff"
  primaryColor = "#57cc8a"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

[[menu.main]]
    identifier = "home"
    name = "Inici"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "Sobre mi"
    url = "/about/"
    weight = 2

[[menu.main]]
  identifier = "tags"
  name = "Etiquetes"
  url = "/tags/"
  weight = 3

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 4

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[params.social]]
    url = "jnorbu8@gmail.com"
    name = "Correu"
    icon = "mail"

[[params.social]]
    url = "https://github.com/notesgnu"
    name = "github"
    icon = "github"

[[params.social]]
    url = "https://twitter.com/manelsales"
    name = "Twitter"
    icon = "twitter"

[[params.social]]
    url = "https://mastodont.cat/@msaliko"
    name = "Mastodon"
    icon = "star"

[[params.social]]
    url = "https://croniqueslinux.wordpress.com/"
    name = "Wordpress"
    icon = "file-text"
